# ./Dockerfile

FROM node:13.7

ARG HOST
ARG PORT
ARG NEO4J_PROTOCOL
ARG NEO4J_HOST
ARG NEO4J_PORT
ARG NEO4J_USERNAME
ARG NEO4J_PASSWORD
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET

ENV HOST=${HOST}
ENV PORT=${PORT}
ENV NEO4j_PROTOCOL=${NEO4j_PROTOCOL}
ENV NEO4J_HOST=${NEO4J_HOST}
ENV NEO4J_PORT=${NEO4J_PORT}
ENV NEO4J_USERNAME=${NEO4J_USERNAME}
ENV NEO4J_PASSWORD=${NEO4J_PASSWORD}
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}

WORKDIR /app/

COPY package*.json /app/
RUN npm install
COPY . /app/

EXPOSE ${PORT}
CMD [ "npm", "run", "start" ]