#!/bin/bash

docker build -t signifycommunity/backend:common-backend \
--build-arg HOST=$HOST \
--build-arg PORT=$PORT \
--build-arg NEO4J_HOST=$NEO4J_PROTOCOL \
--build-arg NEO4J_HOST=$NEO4J_HOST \
--build-arg NEO4J_PORT=$NEO4J_PORT \
--build-arg NEO4J_USERNAME=$NEO4J_USERNAME \
--build-arg NEO4J_PASSWORD=$NEO4J_PASSWORD \
--build-arg FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID \
--build-arg FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET \
.

